import * as AbstractFactoryPattern from './AbstractFactoryPattern';
import * as AdapterPattern from './AdapterPattern';
import * as BridgePattern from './BridgePattern';
import * as BuilderPattern from './BuilderPattern';
import * as ChainOfResponsibilityPattern from './ChainOfResponsibilityPattern';
import * as CommandPattern from './CommandPattern';
import * as CompositePattern from './CompositePattern';
import * as DecoratorPattern from './DecoratorPattern';
import * as FacadePattern from './FacadePattern';
import * as FactoryPattern from './FactoryPattern';
import * as FilterPattern from './FilterPattern';
import * as FlyweightPattern from './FlyweightPattern';
import * as InterpreterPattern from './InterpreterPattern';
import * as IteratorPattern from './IteratorPattern';
import * as PrototypePattern from './PrototypePattern';
import * as ProxyPattern from './ProxyPattern';
import * as SingletonPattern from './SingletonPattern';

AbstractFactoryPattern.run();
AdapterPattern.run();
BridgePattern.run();
BuilderPattern.run();
ChainOfResponsibilityPattern.run();
CommandPattern.run();
CompositePattern.run();
DecoratorPattern.run();
FacadePattern.run();
FactoryPattern.run();
FilterPattern.run();
FlyweightPattern.run();
InterpreterPattern.run();
IteratorPattern.run();
PrototypePattern.run();
ProxyPattern.run();
SingletonPattern.run();
